/* Generated for the ThinkMeta.ConcurrentTasks MSVC build: forwards to the
 * Windows-specific config header that ships with the LAME sources instead
 * of one generated by autoconf/configure. */
#include "configMS.h"
